import { Post, Story, TrendingDestination, User, Comment } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'wanderlust_maya',
    displayName: 'Maya Chen',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80',
    bio: 'Travel photographer & hotel connoisseur 📸 | 47 countries & counting | Posts earn me real commissions — book through my links!',
    followerCount: 24800,
    followingCount: 891,
    postCount: 234,
    totalEarnings: 1284.50,
    isAI: false,
    isVerified: true,
    location: 'Nomadic 🌍',
    isFollowing: false,
  },
  {
    id: '2',
    username: 'pacific_explorer',
    displayName: 'Liam Torres',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&q=80',
    bio: 'Southeast Asia specialist | Budget to luxury | DM for travel tips ✈️',
    followerCount: 8920,
    followingCount: 445,
    postCount: 89,
    totalEarnings: 456.20,
    isAI: false,
    isVerified: false,
    location: 'Bangkok, Thailand',
    isFollowing: true,
  },
  {
    id: 'ai-1',
    username: 'osvasa_picks',
    displayName: 'Osvasa Picks',
    avatar: 'https://images.unsplash.com/photo-1614289371518-722f2615943d?w=150&h=150&fit=crop&q=80',
    bio: 'AI-curated travel recommendations from around the world ✨ Discover hidden gems and iconic stays.',
    followerCount: 142000,
    followingCount: 0,
    postCount: 1847,
    totalEarnings: 0,
    isAI: true,
    isVerified: true,
    location: 'Everywhere',
    isFollowing: false,
  },
  {
    id: '3',
    username: 'euro_escapes',
    displayName: 'Sophie Laurent',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&q=80',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    bio: 'Paris-based travel writer | Hotels & hidden gems across Europe 🗺️ | Sharing my best finds',
    followerCount: 31500,
    followingCount: 712,
    postCount: 178,
    totalEarnings: 2109.80,
    isAI: false,
    isVerified: true,
    location: 'Paris, France',
    isFollowing: false,
  },
  {
    id: 'ai-2',
    username: 'osvasa_eats',
    displayName: 'Osvasa Eats',
    avatar: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=150&h=150&fit=crop&q=80',
    bio: 'AI-curated dining experiences worldwide 🍽️ From street food to Michelin stars.',
    followerCount: 89000,
    followingCount: 0,
    postCount: 934,
    totalEarnings: 0,
    isAI: true,
    isVerified: true,
    location: 'Worldwide',
    isFollowing: false,
  },
];

export const mockPosts: Post[] = [
  {
    id: '1',
    user: mockUsers[0],
    image: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=900&h=675&fit=crop&q=85',
    location: 'Baa Atoll, Maldives',
    country: 'Maldives',
    countryCode: 'MV',
    category: 'hotel',
    title: 'Four Seasons Resort Maldives at Landaa Giraavaru',
    description:
      "Woke up to this view this morning 😭 The overwater villa at Four Seasons Baa Atoll is next-level. UNESCO Biosphere Reserve surroundings, house reef steps from your deck, and the most stunning sunsets I've ever witnessed. Every morning starts with a private plunge pool dip and breakfast delivered by boat. If you're treating yourself to one splurge this year — make it this.",
    expediaUrl: 'https://expedia.com/affiliates/osvasa/socialtravel',
    likeCount: 4892,
    commentCount: 234,
    shareCount: 891,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    tags: ['maldives', 'overwater', 'luxury', 'fourseasons', 'travel'],
    price: 'from $1,200/night',
    rating: 9.8,
    propertyType: 'Overwater Villa',
  },
  {
    id: '2',
    user: mockUsers[2],
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=900&h=675&fit=crop&q=85',
    location: 'Ubud, Bali',
    country: 'Indonesia',
    countryCode: 'ID',
    category: 'hotel',
    title: "Komaneka at Bisma — Ubud's Jungle Hideaway",
    description:
      "Perched above the Campuhan Ridge, Komaneka at Bisma offers an unforgettable Ubud experience. Each villa features a private plunge pool overlooking an endless jungle canopy, with Balinese architecture blending seamlessly into the landscape. The spa is exceptional — book the signature rice ritual treatment and the jungle walk at dawn. This is what Bali is supposed to feel like.",
    expediaUrl: 'https://expedia.com/affiliates/osvasa/socialtravel',
    likeCount: 3241,
    commentCount: 87,
    shareCount: 445,
    isLiked: true,
    isSaved: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    tags: ['bali', 'ubud', 'jungle', 'villa', 'indonesia'],
    price: 'from $380/night',
    rating: 9.5,
    propertyType: 'Jungle Villa',
  },
  {
    id: '3',
    user: mockUsers[1],
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&h=675&fit=crop&q=85',
    location: 'Positano, Amalfi Coast',
    country: 'Italy',
    countryCode: 'IT',
    category: 'restaurant',
    title: 'La Tagliata — Best Meal of My Life',
    description:
      "You have to earn this meal — it's a 20-minute hike up the hills above Positano. But the views, the antipasto spread, the handmade pasta... absolutely worth every step. They don't take reservations; just show up early and wait for a table. Cash only. Go at sunset. Trust me, this will be one of those meals you talk about for years.",
    expediaUrl: 'https://expedia.com/affiliates/osvasa/socialtravel',
    likeCount: 2187,
    commentCount: 156,
    shareCount: 334,
    isLiked: false,
    isSaved: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    tags: ['positano', 'italy', 'amalfi', 'food', 'restaurant'],
    price: '~$45/person',
    rating: 9.9,
  },
  {
    id: '4',
    user: mockUsers[3],
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=900&h=675&fit=crop&q=85',
    location: 'Oia, Santorini',
    country: 'Greece',
    countryCode: 'GR',
    category: 'destination',
    title: 'Santorini in January — The Best Kept Secret',
    description:
      "Everyone tells you to visit Santorini in summer. Everyone is wrong. January brings empty caldera paths, no queues at sunset spots, €80/night cliffside suites, and a raw, moody beauty that the summer crowds simply can't experience. The island belongs to you. The light is extraordinary. Restaurants are unhurried. Stay at least 4 nights.",
    expediaUrl: 'https://expedia.com/affiliates/osvasa/socialtravel',
    likeCount: 8934,
    commentCount: 612,
    shareCount: 2341,
    isLiked: true,
    isSaved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    tags: ['santorini', 'greece', 'offseason', 'europe', 'travel'],
    rating: 9.7,
  },
  {
    id: '5',
    user: mockUsers[2],
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=900&h=675&fit=crop&q=85',
    location: 'Shinjuku, Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    category: 'destination',
    title: 'Tokyo After Dark — Shinjuku Neon Guide',
    description:
      "Tokyo's Shinjuku district is a sensory overload in the best possible way. From the intimate Golden Gai alleyways packed with 6-seat bars to the electric energy of Kabukicho, Shinjuku offers a lifetime of exploration within a few city blocks. Best experienced on foot after 9pm. Stay nearby for total immersion.",
    expediaUrl: 'https://expedia.com/affiliates/osvasa/socialtravel',
    likeCount: 12445,
    commentCount: 889,
    shareCount: 4112,
    isLiked: false,
    isSaved: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    tags: ['tokyo', 'japan', 'shinjuku', 'nightlife', 'asia'],
    rating: 9.6,
  },
  {
    id: '6',
    user: mockUsers[4],
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=900&h=675&fit=crop&q=85',
    location: 'Tulum, Mexico',
    country: 'Mexico',
    countryCode: 'MX',
    category: 'restaurant',
    title: 'Hartwood — Jungle Fine Dining, No Electricity',
    description:
      "Hartwood runs entirely on fire and solar power. There's no electricity, no gas, no refrigeration — just wood-fired magic and the freshest local ingredients. Tables face the jungle. The menu changes nightly. Reserve months ahead, or show up at 5pm and wait on the list. Order the whole fish. Order everything.",
    expediaUrl: 'https://expedia.com/affiliates/osvasa/socialtravel',
    likeCount: 6723,
    commentCount: 341,
    shareCount: 1205,
    isLiked: false,
    isSaved: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    tags: ['tulum', 'mexico', 'finedining', 'jungle', 'foodie'],
    price: '~$80/person',
    rating: 9.7,
  },
];

export const mockComments: Comment[] = [
  {
    id: 'c1',
    user: mockUsers[1],
    text: 'This is literally on my bucket list 🙌 How many nights did you stay?',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    likeCount: 24,
  },
  {
    id: 'c2',
    user: mockUsers[3],
    text: 'The overwater villas are unreal. We went for our honeymoon — worth every penny!',
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    likeCount: 57,
  },
  {
    id: 'c3',
    user: mockUsers[0],
    text: 'Stayed 5 nights! Could have stayed forever honestly. Book early — it fills up fast.',
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    likeCount: 91,
  },
];

export const mockStories: Story[] = [
  {
    id: 's1',
    user: mockUsers[0],
    destination: 'Maldives',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=200&h=200&fit=crop&q=80',
  },
  {
    id: 's2',
    user: mockUsers[2],
    destination: 'Kyoto',
    image: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=200&h=200&fit=crop&q=80',
  },
  {
    id: 's3',
    user: mockUsers[1],
    destination: 'Bangkok',
    image: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=200&h=200&fit=crop&q=80',
  },
  {
    id: 's4',
    user: mockUsers[3],
    destination: 'Paris',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=200&h=200&fit=crop&q=80',
  },
  {
    id: 's5',
    user: { ...mockUsers[4], id: 's5-user', username: 'beach_dreams', displayName: 'Beach Dreams' },
    destination: 'Phuket',
    image: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=200&h=200&fit=crop&q=80',
  },
  {
    id: 's6',
    user: { ...mockUsers[1], id: 's6-user', username: 'alps_adventures', displayName: 'Alps Adventures' },
    destination: 'Zurich',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=200&h=200&fit=crop&q=80',
  },
  {
    id: 's7',
    user: { ...mockUsers[0], id: 's7-user', username: 'morocco_magic', displayName: 'Morocco Magic' },
    destination: 'Marrakech',
    image: 'https://images.unsplash.com/photo-1539020140153-e479b8be4046?w=200&h=200&fit=crop&q=80',
  },
];

export const trendingDestinations: TrendingDestination[] = [
  {
    id: 't1',
    name: 'Bali',
    country: 'Indonesia',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=100&h=100&fit=crop&q=80',
    postCount: 8934,
  },
  {
    id: 't2',
    name: 'Santorini',
    country: 'Greece',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=100&h=100&fit=crop&q=80',
    postCount: 7123,
  },
  {
    id: 't3',
    name: 'Tokyo',
    country: 'Japan',
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=100&h=100&fit=crop&q=80',
    postCount: 6891,
  },
  {
    id: 't4',
    name: 'Maldives',
    country: 'Maldives',
    image: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=100&h=100&fit=crop&q=80',
    postCount: 5234,
  },
];
